kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: beispiel
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'beispiel:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/lukeelten/nginx-example.git'
  triggers:
    - type: ConfigChange
  runPolicy: Serial

