kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: docker-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'docker-build:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'ruby:2.5'
      env:
        - name: EXAMPLE
          value: sample-app
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-hello-world.git'
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial

