kind: Deployment
apiVersion: apps/v1
metadata:
  name: access-host
  labels:
    app: access-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-host
  template:
    metadata:
      labels:
        app: access-host
    spec:
      serviceAccount: access-host
      containers:
        - name: ubi
          imagePullPolicy: Always
          image: registry.access.redhat.com/ubi8/ubi:latest
          volumeMounts:
            - name: etc
              mountPath: /host/etc
#          securityContext:
#            runAsUser: 0
#            privileged: true
          args:
            - cat
            - /host/etc/passwd
      volumes:
        - name: etc
          hostPath:
            path: /etc
            type: ''
